# https://github.com/igorshubovych/markdownlint-cli#configuration

# disable line length errors
MD013: false

# disable inline HTML errors
MD033: false

# disable first line in a file should be a top-level heading
MD041: false
